controller_list:
  - name: fake_rasm_arm_controller
    joints:
      - link_z_1
      - link_s_2
      - link_e_3
      - link_y_4
      - link_p_5
  - name: fake_tobii_screen_controller
    joints:
      - link_r_6
initial:  # Define initial robot poses.
  - group: rasm_arm
    pose: screen_up