controller_list:
  - name: fake_rasm_position_controller
    joints:
      - link_z_1
      - link_s_2
      - link_e_3
  - name: fake_rasm_orientation_controller
    joints:
      - link_y_4
      - link_p_5
      - link_r_6
initial:  # Define initial robot poses.
  - group: rasm_position
    pose: arm_home
  - group: rasm_orientation
    pose: screen_up