# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rasm_position
  joint_model_group_pose: arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - link_z_1
    - link_s_2
    - link_e_3
    - link_y_4
    - link_p_5
    - link_r_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []