controller_list:
 - name: rasm_urdf/arm_joint_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - link_z_1
    - link_s_2
    - link_e_3
    - link_y_4
    - link_p_5
    - link_r_6
initial:
  - group:  full_rasm
    pose:   screen_up
