controller_list:
  - name: fake_full_rasm_controller
    joints:
      - link_z_1
      - link_s_2
      - link_e_3
      - link_y_4
      - link_p_5
      - link_r_6
initial:  # Define initial robot poses.
  - group: full_rasm
    pose: screen_up