# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  link_e_3:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  link_p_5:
    max_position: 0.785
    min_position: -2.13
    has_velocity_limits: true
    max_velocity: 0.15
    has_acceleration_limits: true
    max_acceleration: 0.075
  link_r_6:
    max_position: 1.57
    min_position: -1.57
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.25
  link_s_2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  link_y_4:
    max_position: 2.53
    min_position: -2.53
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.25
  link_z_1:
    has_velocity_limits: false
    max_velocity: 0.009
    has_acceleration_limits: false
    max_acceleration: 0.00025
    has_jerk_limits: false
    max_jerk: 5.0
