rasm_urdf:
  # Publish all joint states ---------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers -------------------------------
  height_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_z_1
    pid: {p: 1.0, i: 1.0, d: 1.0}
  shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_s_2
    pid: {p: 1.0, i: 1.0, d: 0.0}
  elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_e_3
    pid: {p: 1.0, i: 1.0, d: 1.0}
  yaw_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_y_4
    pid: {p: 1.0, i: 1.0, d: 1.0}
  pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_p_5
    pid: {p: 1.0, i: 1.0, d: 1.0}
  roll_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_r_6
    pid: {p: 1.0, i: 1.0, d: 1.0}
