# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: full_rasm
  joint_model_group_pose: screen_up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - link_z_1
    - link_s_2
    - link_e_3
    - link_y_4
    - link_p_5
    - link_r_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
rasm_urdf:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  rasm_position_controller:
    type: effort_controllers/JointPositionController
    joints:
        - link_z_1
        - link_s_2
        - link_e_3
        - link_y_4
        - link_p_5
        - link_r_6
    gains:
      link_z_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      link_s_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      link_e_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      link_y_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      link_p_5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      link_r_6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
# Added everything under controller_list originally it just had []
controller_list:
- name: rasm_urdf/rasm_position_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - link_z_1
    - link_s_2
    - link_e_3
    - link_y_4
    - link_p_5
    - link_r_6
