rasm_urdf:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  arm_joint_controller:
    type: "pos_vel_acc_controllers/JointTrajectoryController"
    joints:
      - link_z_1
      - link_s_2
      - link_e_3
      - link_y_4
      - link_p_5
      - link_r_6
